import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | AUREXIS SOLUTION",
  description: "Review the terms governing your use of AUREXIS SOLUTION's website, client portals, and digital services.",
};

export default function TermsOfServicePage() {
  return (
    <section className="bg-[#05060c] py-16 text-neutral-300">
      <div className="mx-auto max-w-4xl px-6 space-y-10">
        <header className="space-y-4">
          <p className="text-xs uppercase tracking-[0.3em] text-cyan-400/80">Agreement</p>
          <h1 className="text-4xl font-semibold text-white">Terms of Service</h1>
          <p className="text-sm text-neutral-400">Effective Date: March 2026</p>
        </header>

        <article className="space-y-8 leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing the AUREXIS SOLUTION website, booking a Strategy Session, or logging into our secure Client Portal,
              you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you are
              prohibited from using our site and services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-white">2. Intellectual Property &amp; Ownership</h2>
            <p>
              All content, UI/UX designs, website architecture, and branding on the public AUREXIS SOLUTION website remain our exclusive intellectual property.
              For custom projects, the transfer of intellectual property rights to the client occurs only upon full execution of a Master Service Agreement
              and payment of all related invoices. Until then, AUREXIS SOLUTION retains ownership of any developed infrastructure.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-white">3. Artificial Intelligence (AI) Liability Disclaimer</h2>
            <p>
              AUREXIS SOLUTION deploys automation powered by third-party Large Language Models (LLMs) and AI APIs. You acknowledge that
              these models are probabilistic, and AUREXIS SOLUTION is not liable for "hallucinations," inaccurate outputs, or anomalous behaviors
              generated by third-party providers once deployed. We are also not responsible for service interruptions, rate limits, or policy changes enforced by external AI vendors.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-white">4. Client Portal Conduct &amp; Termination</h2>
            <p>
              Access to the Aurexis Client Portal and Telegram-integrated priority support is reserved for active partners. We reserve the right to suspend or terminate access
              without notice if a user fails payment obligations, attempts to reverse-engineer or disrupt our infrastructure, or engages in abusive behavior toward our team.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-white">5. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, AUREXIS SOLUTION is not liable for indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill,
              arising from your use or inability to use our website or developed applications, downtime from third-party hosts (e.g., Vercel, AWS), or cyber-attacks.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-white">6. Governing Law</h2>
            <p>
              These Terms of Service are governed by the laws of Malaysia, without regard to conflict of law provisions. Any disputes shall be resolved in Malaysian courts.
            </p>
          </section>
        </article>
      </div>
    </section>
  );
}
